### ISSUE TITLE
Add file_storage endpoint

### ISSUE THREAD

**Issue by Chasky-H** [Pepperi-Addons/papi-sdk#17]
@OrenVildermanPepperi 

I need to use this in my addon.

If you don't have time to finish it. Please reassign the task to me, and I will do it myself.

Thanks

**Comment by OrenVildermanPepperi** [comment]
@Chasky-H Since I committed this working endpoint that I created,
I was asked to do other things that will probably end tomorrow, can this be postpone to the first few days of the next week?
![image](https://user-images.githubusercontent.com/66742740/85510696-680a9280-b600-11ea-99b0-11bf518592d2.png)

**Comment by OrenVildermanPepperi** [comment]
@ido-pepperi - FYI

**Comment by Chasky-H** [comment]
Sure. The longer you push it off, the harder it will be for you to merge master into your branch.
Just don't wait 'til you finish writing all the tests.
